### ISSUE TITLE
When using ForceIP, why does the subnet mask need to be 255.255.255.0?

### ISSUE THREAD

**Issue by HorPaella** [Touseefelahi/GigeVision#107]
When using ForceIP, it will not work unless the computer's subnet mask is 255.255.255.0. 
Why are other subnet masks not permitted?

GigeVision.Core/Services/Gvcp.cs　ForceIPAsync
GigeVision.Core/Services/OtherServices/NetworkService.cs　GetAllInterfaces

**Comment by Touseefelahi** [comment]
yes, it should be fixed, it is not supposed to be like this

**Comment by CosbyBs86** [comment]
Having the IDE opened for other changes that @Touseefelahi already applied to master, I did the fix (https://github.com/Touseefelahi/GigeVision/pull/114).
