### ISSUE TITLE
No payload seems to be sent by camera

### ISSUE THREAD

**Issue by blauertee** [Touseefelahi/GigeVision#119]
Hello, 

My camera doesnt seem to send any actual Image data on `StartStreamAsync()` I can see the metadata (LEADER and TRAILER) packages but there is no actual data in between them (see wireshark table provided in #118 ). Anyone has any Idea whats going south?

Thanks!!

**Comment by Touseefelahi** [comment]
Yes in the provided wireshark table, it doesn't have the actual image data. I can think of two possible issues:
1: Packetsize is supposed to be within the supported MTU size. Try setting a lower packet size of 1400. You can also enable Jumbo packet support from your network settings to use higher packet size.
2: Driver issue for the Ethernet Card.

**Comment by blauertee** [comment]
> 1: Packetsize is supposed to be within the supported MTU size. Try setting a lower packet size of 1400. You can also enable Jumbo packet support from your network settings to use higher packet size. 

Great, solved it!
