### ISSUE TITLE
Recommend

### ISSUE THREAD

**Issue by YorkWong1995** [Touseefelahi/GigeVision#71]
I have met a problem which leads to program crashed.
When set payloadsize in **CalculateSingleRowPayload**, at first i set payloadsize with the formula (width x height x pixel
size).
After i read gige vision spec2.0, it says **It is strongly recommended to retrieve PayloadSize from the camera instead of relying on the above formula.** 
Finally i solved this issue by using specific payload size.

**Comment by Touseefelahi** [comment]
@YorkWong1995 Actually, the library sets the payload by using that formula.
I would recommend you use higher Payloadsize by enabling the Jumbo packet to get a stable stream. 
To enable the jumbo packet you need to configure it from the ethernet adaptor properties.
