### ISSUE TITLE
program crashed after receive socket reply

### ISSUE THREAD

**Issue by YorkWong1995** [Touseefelahi/GigeVision#87]
I wanna to got the data in UdpReceiveResult.Result.buffer in SendGvcpCommand function.
but When i got reply from socket, and run **reply.Result.Buffer != null** , it suddenly crashed with no exception. use wireshark there is no any data.  
Do u know what will lead to this problem
here is my code.
![cap](https://user-images.githubusercontent.com/54474676/205200002-f24f3239-36ef-4da2-ae43-ebc17fea8c27.JPG)

thanks in advance.

**Comment by YorkWong1995** [comment]
In debug mode , sometimes , reply.Result.buffer is now  at first , but when it runs **reply.Result.Buffer != null**, reply.Result.buffer got data, it is not null any more. and i do not find the reason, too.  In this situation, wireshark will get the return package.

**Comment by YorkWong1995** [comment]
It seems  receiveasync is Asynchronous method 
so when i want to compare reply.result.buffer with null 
reply is receiving data, meanwhile , i want to get the reply value to do comparation

**Comment by Touseefelahi** [comment]
@YorkWong1995 this is not related to the library. 
You must understand how asynchronous methods work. You must wait for it to finish before doing anything with the result.
From this snippet, it seems like you are not using the library properly.

**Comment by YorkWong1995** [comment]
I also used **if (await Task.WhenAny(reply, Task.Delay(socketTx.Client.ReceiveTimeout)).ConfigureAwait(false) == reply)** to wait the method finished.
but in debug mode, this condition is never satisfy. 
the reply status is always waitingforactivation, but wireshark already caught the return package.

In another word, i used **var ret = await Task.WhenAny(reply, Task.Delay(socketTx.Client.ReceiveTimeout)).ConfigureAwait(false);**  the status of ret is always different from the reply‘s

**Comment by YorkWong1995** [comment]
After **Task<UdpReceiveResult> reply = socketTx.ReceiveAsync();**
I used **await reply;** ,Sometimes, it will crushed.
I used **if (await Task.WhenAny(reply, Task.Delay(socketTx.Client.ReceiveTimeout)).ConfigureAwait(false) == reply)** ,Sometimes,  it also crushed.
And i am  confused,because wireshark sometimes can get the reply package, when the library crashed .

**Comment by Touseefelahi** [comment]
can you comment the whole method?

**Comment by YorkWong1995** [comment]
This problem is not related to library
