### ISSUE TITLE
FrameReady not fired

### ISSUE THREAD

**Issue by nadavbeno** [Touseefelahi/GigeVision#90]
Hi, what can I do if FrameReady is not fired?
The camera is connected, I pressed on start stream, the UpdateFps is fired, but fps count is always 0.

**Comment by Touseefelahi** [comment]
check for the Updates by hooking to the Updates event https://github.com/Touseefelahi/GigeVision/blob/886b2bf9eed74699e08179b717c3dfd83191f28e/GigeVision.Core/Interfaces/ICamera.cs#L13

You must allow exception to the firewall to receive the GVSP stream

**Comment by nadavbeno** [comment]
Updates is null...
I disabled my firewall and still don't see nothing, and fps counter stays on 0

**Comment by Touseefelahi** [comment]
Try increasing the mtu size. Go to network settings and increase the mtu size to max: 9000

Let me know it it fixes the issue

**Comment by nadavbeno** [comment]
I can set it only up to 1500
![image](https://user-images.githubusercontent.com/26343491/235068434-b040669c-4333-4b84-a923-8aa59d7f5424.png)

and getting the message:
A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.

**Comment by Touseefelahi** [comment]
Okay then manually set the packet size to 1400 and test. The property name would be Payload or PacketSize in Camera class.

**Comment by nadavbeno** [comment]
Works!
Thanks!

**Comment by Touseefelahi** [comment]
Great!
Now just to check, I believe you can increase the mtu size from control panel, from network driver settings. Do a little search about it.
