### ISSUE TITLE
Error connecting the camera

### ISSUE THREAD

**Issue by vo1s** [Touseefelahi/GigeVision#95]
Using GigeVisionLibrary.Test.Console example to test camera stream. getting this error "Update from Library: Object reference not set to an instance of an object.". Camera is found. Nothing in code changed by me.
![Screenshot_11](https://github.com/Touseefelahi/GigeVision/assets/46219207/9ce096e3-cc39-4e34-a4ee-e48ad21495d8)

**Comment by Touseefelahi** [comment]
I believe the library is not able to get the decode the xml file properly. Check if the registers are being read properly

**Comment by vo1s** [comment]
> I believe the library is not able to get the decode the xml file properly. Check if the registers are being read properly

How do I check it? Please help

**Comment by Touseefelahi** [comment]
https://github.com/Touseefelahi/GigeVision/blob/master/GigeVision.Core/Services/Gvcp.cs#L812

Go to this function and step in line by line while debugging. Let me know if this function is working fine or not?

**Comment by vo1s** [comment]
this line `(byte[], string) valueTuple1 = await this.GetRawXmlFileFromCamera(ip).ConfigureAwait(false);` is setting xmlFile to null and it doesnt go any further. And this line gets ip from camera, so it is not the problem

**Comment by Touseefelahi** [comment]
so it is not reading the XML properly, It would require more information to know the issue, share your email ID or contact me @ touseefelahi@ymail.com, I'll contact you when I get time.

**Comment by vo1s** [comment]
voisechannel@gmail.com
